import * as Phaser from 'phaser';
import {LEVELS,SPECIES,STAGE_NAME,WORLDS} from '../game/content';
import {rules} from '../game/config';
import {SaveStore,totalStars,unlocked,type Profile} from '../platform/storage';
import {connectSync} from '../platform/sync';
import {Audio} from '../platform/audio';
import {PlayScene} from '../scenes/PlayScene';
import type {Result} from '../game/types';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export class App {
 private ui=document.getElementById('ui')!;private profile:Profile|null=null;private screen='splash';private syncStatus='Saves on this device';private install?:InstallEvent;
 readonly store=new SaveStore();readonly audio=new Audio();
 constructor(private game:Phaser.Game){
  this.audio.enabled=this.store.settings.sound!==false;game.registry.set('audio',this.audio);
  game.registry.set('reducedMotion',this.reducedMotion);
  window.addEventListener('rex-ready',()=>this.splash());
  window.addEventListener('rex-pause',()=>this.pause());
  window.addEventListener('rex-end',((e:CustomEvent<Result>)=>this.results(e.detail)) as EventListener);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();this.install=e as InstallEvent});
  this.store.onChange=()=>{if(this.screen==='map')this.map();else if(this.screen==='profiles')this.profiles()};
  this.ui.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;this.audio.unlock();this.audio.play('click');this.action(button.dataset.action!,button.dataset.value)});
  // A live system setting change restarts decorative animation without touching rules.
  matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{game.registry.set('reducedMotion',this.reducedMotion);document.body.classList.toggle('reduced-motion',this.reducedMotion)});
  this.splash();void connectSync(this.store,s=>{this.syncStatus=s;const badge=document.querySelector('[data-sync]');if(badge)badge.textContent=s});
 }
 private get reducedMotion(){return this.store.settings.motion===false||matchMedia('(prefers-reduced-motion: reduce)').matches}
 private button(label:string,action:string,value?:string,classes='',disabled=false){return `<button class="button ${classes}" data-action="${action}" ${value===undefined?'':`data-value="${esc(value)}"`} ${disabled?'disabled':''}>${label}</button>`}
 private shell(screen:string,content:string){this.screen=screen;this.ui.className=screen;document.body.dataset.screen=screen;this.ui.innerHTML=content;this.ui.scrollTop=0;const heading=this.ui.querySelector<HTMLElement>('h1,h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}}
 private nav(){return `<nav>${this.button('Valleys','map',undefined,'quiet')}${this.button('Dino Book','book',undefined,'quiet')}${this.button('Family','leaderboard',undefined,'quiet')}</nav>`}
 private top(title:string,subtitle:string){return `<header class="page-heading"><div><p class="eyebrow">TINY REX · VALLEY ADVENTURES</p><h1>${title}</h1><p>${subtitle}</p></div>${this.button('←','map',undefined,'icon quiet')}</header>`}
 private footer(){return `<footer><span data-sync>${esc(this.syncStatus)}</span>${this.button(this.audio.enabled?'Sound on':'Sound off','sound',undefined,'quiet small')}${this.button('Help & install','help',undefined,'quiet small')}</footer>`}
 splash(){
  this.game.scene.stop('Play');if(!this.game.scene.isActive('Menu'))this.game.scene.start('Menu');
  const last=this.store.profiles.find(p=>p.id===this.store.settings.lastProfile);
  this.shell('splash',`<div class="splash-content"><p class="eyebrow">A LITTLE DINOSAUR. A VERY BIG ADVENTURE.</p><h1 class="wordmark">TINY <span>REX</span></h1><p class="tagline">Eat small. Grow mighty.</p><div class="hero-space" aria-hidden="true"></div><div class="splash-bottom"><p>Four wild valleys. Twenty brave hunts.<br>One tiny Rex with a very big appetite.</p>${last?this.button('Keep going as '+esc(last.name),'select',last.id,'primary big'):this.button('Start hatching →','profiles',undefined,'primary big')}${last?this.button('Choose a player','profiles',undefined,'quiet'):''}<p class="hint">Tap or drag to run · Arrow keys or WASD</p>${this.footer()}</div></div>`);
 }
 profiles(){this.game.scene.stop('Play');if(!this.game.scene.isActive('Menu'))this.game.scene.start('Menu');this.shell('profiles',`<section class="panel">${this.top('Who’s hatching?','Your adventures, stars and discoveries stay with you.')}<div class="profile-list">${this.store.profiles.map(p=>this.button(`<span class="avatar">${esc(p.avatar)}</span><span><b>${esc(p.name)}</b><small>${totalStars(this.store.progress(p.id))} stars · ${Object.keys(this.store.progress(p.id).met).length} discoveries${p.pin?' · PIN protected':''}</small></span> →`,'select',p.id,'profile')).join('')}</div>${this.button('+ New hatchling','new',undefined,'primary')}${this.button('Back','splash',undefined,'quiet')}${this.footer()}</section>`)}
 private select(id:string){const profile=this.store.profiles.find(p=>p.id===id);if(!profile)return;if(profile.pin){this.modal(`<h2>Welcome back, ${esc(profile.name)}</h2><p>Enter your family PIN.</p><form id="pin-form"><label>PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="off"></label><p class="form-error" role="alert"></p><button class="button primary">Let’s go →</button></form>${this.button('Cancel','close',undefined,'quiet')}`);document.querySelector<HTMLFormElement>('#pin-form')!.onsubmit=e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;if(new FormData(form).get('pin')!==profile.pin){form.querySelector('.form-error')!.textContent='That PIN doesn’t match. Try again.';return}this.enter(profile)};}else this.enter(profile)}
 private enter(p:Profile){this.profile=p;this.store.write('settings',{...this.store.settings,lastProfile:p.id});this.map()}
 private newProfile(){this.modal(`<p class="eyebrow">YOUR ADVENTURE STARTS HERE</p><h2>A new hatchling</h2><form id="profile-form"><label>Your name<input name="name" maxlength="24" required autocomplete="off" placeholder="What should Rex call you?"></label><label>Your avatar<select name="avatar">${['🦖','🦕','🐊','🦎','🐢','🐉','🦊','🐻','🦉','⭐'].map(a=>`<option>${a}</option>`).join('')}</select></label><label>Family PIN <small>Optional · four digits</small><input name="pin" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" type="password" autocomplete="off"></label><p class="form-error" role="alert"></p><button class="button primary">Start my adventure →</button></form>${this.button('Cancel','close',undefined,'quiet')}`);document.querySelector<HTMLFormElement>('#profile-form')!.onsubmit=e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,data=new FormData(form),name=String(data.get('name')).trim();if(!name){form.querySelector('.form-error')!.textContent='Please give your hatchling a name.';return}const p=this.store.add(name,String(data.get('avatar')),String(data.get('pin'))||null);this.enter(p)}}
 map(){
  if(!this.profile)return this.profiles();this.game.scene.stop('Play');if(!this.game.scene.isActive('Menu'))this.game.scene.start('Menu');
  const progress=this.store.progress(this.profile.id),next=unlocked(progress),wins=Object.keys(progress.levels).length;
  this.shell('map',`<section class="panel map-panel"><header class="page-heading"><div><p class="eyebrow">YOUR PREHISTORIC ADVENTURE</p><h1>${esc(this.profile.avatar)} ${esc(this.profile.name)}’s valleys</h1><p><span class="gold">★ ${totalStars(progress)} / 60</span> · ${Object.keys(progress.met).length} discoveries</p></div>${this.button('Players','profiles',undefined,'quiet small')}</header><div class="continue-card"><div><p class="eyebrow">${wins===20?'HUNT AGAIN':'NEXT ADVENTURE'}</p><h2>${esc(LEVELS[next].name)}</h2><p>${esc(LEVELS[next].hint)}</p></div>${this.button('Hunt →','brief',String(next),'primary')}</div><div class="valleys">${WORLDS.map((world,wi)=>`<section class="valley valley-${world.id}"><header><span class="world-icon">${world.icon}</span><div><p class="eyebrow">VALLEY ${wi+1}</p><h2>${world.name}</h2></div><span class="world-stars">${LEVELS.filter(l=>l.world===wi).reduce((n,l)=>n+(progress.levels[l.idx]?.stars||0),0)}/15 ★</span></header><p>${world.blurb}</p><div class="hunt-grid">${LEVELS.filter(l=>l.world===wi).map(l=>`<button class="hunt ${l.idx===next?'next':''}" data-action="brief" data-value="${l.idx}" ${l.idx>next?'disabled':''} aria-label="Hunt ${l.idx+1}, ${esc(l.name)}, ${progress.levels[l.idx]?.stars||0} stars"><span class="hunt-number">${l.idx>next?'🔒':String(l.idx+1).padStart(2,'0')}</span><span class="hunt-name">${l.name}</span><span class="hunt-stars">${'★'.repeat(progress.levels[l.idx]?.stars||0)}${'☆'.repeat(3-(progress.levels[l.idx]?.stars||0))}</span>${l.beast?'<span class="beast-badge">BEAST</span>':''}</button>`).join('')}</div></section>`).join('')}</div><div class="feast-card"><p class="eyebrow">ONE VALLEY. ENDLESS APPETITE.</p><h2>🌋 Endless Feast</h2><p>${wins>=rules.feastUnlock?'Hunt, grow, survive. Your belly empties as the valley gets wilder.':'Finish Fern Hollow to open your endless adventure. '+wins+'/5 hunts complete.'}</p>${this.button(wins>=5?'Enter the Feast →':'Finish Fern Hollow first','feast',undefined,'primary',wins<5)}<p class="hint">Personal best ${progress.feastBest.toLocaleString()}</p></div>${this.nav()}${this.footer()}</section>`)
 }
 private brief(idx:number){if(!this.profile)return;const p=this.store.progress(this.profile.id);if(idx>unlocked(p)||!LEVELS[idx])return;const l=LEVELS[idx];this.modal(`<p class="eyebrow">${WORLDS[l.world].name} · HUNT ${idx+1}</p><h2>${l.name}</h2><div class="brief-growth"><span>${STAGE_NAME[l.start]}</span><b>→</b><span>${STAGE_NAME[l.target]}</span></div><p>${l.hint}</p>${l.beast?`<p class="beast-note">Outgrow ${esc(l.beast.name)}, then catch them when they stop for breath.</p>`:''}<p class="hint">Smaller = dinner. Same size = safe.<br>Three hearts. No rush for stars.</p>${this.button('Let’s hunt →','start',String(idx),'primary big')}${this.button('Back to valleys','close',undefined,'quiet')}`)}
 private start(level:number|null){if(!this.profile)return;if(level===null&&Object.keys(this.store.progress(this.profile.id).levels).length<5)return;this.game.registry.set('reducedMotion',this.reducedMotion);this.game.scene.stop('Menu');this.game.scene.stop('Play');this.shell('playing',`<div class="play-controls">${this.button('Ⅱ Pause','pause',undefined,'quiet')}${this.button(this.audio.enabled?'♪ Sound on':'♪ Sound off','sound',undefined,'quiet')}</div>`);this.game.scene.start('Play',{level});document.getElementById('stage')!.focus()}
 private pause(){this.modal(`<p class="eyebrow">TAKE A BREATHER</p><h2>Your valley can wait.</h2><p>Rex is resting right where you left her.</p>${this.button('Keep hunting →','resume',undefined,'primary big')}${this.button('Start this hunt again','restart',undefined,'quiet')}${this.button('Back to valleys','quit',undefined,'quiet')}`)}
 private results(res:Result){if(!this.profile)return;const progress=this.store.record(this.profile.id,res);this.game.scene.stop('Play');this.game.scene.start('Menu');const feast=res.mode==='feast';this.shell('results',`<section class="result-panel"><p class="eyebrow">${feast?'ENDLESS FEAST':res.win?'HUNT COMPLETE':'EVERY REX STARTS SMALL'}</p><h1>${feast?'What a feast!':res.win?STAGE_NAME[res.tier]+'!':'Have another go'}</h1><div class="hero-space" aria-hidden="true"></div><div class="result-stars" aria-label="${res.stars} stars">${feast?'':Array.from({length:3},(_,i)=>`<span style="--i:${i}">${i<res.stars?'★':'☆'}</span>`).join('')}</div><div class="result-score">${res.score.toLocaleString()}<small>POINTS</small></div><div class="result-stats"><span><b>${res.catches}</b> things eaten</span><span><b>${res.hearts}</b> hearts left</span><span><b>${STAGE_NAME[res.tier]}</b> biggest size</span></div><p class="result-note">${feast?'Your best: '+progress.feastBest.toLocaleString():res.win?res.stars===3?'Not a scratch. You’re a natural.':'You made it! Keep your hearts for more stars.':res.reason==='time'?'The sun went down. Bigger meals help you grow faster.':'Something bigger gave you a fright. Find open ground and watch the red rings.'}</p>${res.win&&!feast&&res.levelIdx<19?this.button('Next adventure →','start',String(res.levelIdx+1),'primary big'):''}${res.win&&res.levelIdx===19?'<p class="gold">All four valleys are yours. Mighty Rex!</p>':''}${this.button(feast?'Feast again':'Hunt again','start',feast?'feast':String(res.levelIdx),'primary')}${this.button('Back to valleys','map',undefined,'quiet')}${this.footer()}</section>`)}
 private book(){if(!this.profile)return;const p=this.store.progress(this.profile.id);this.shell('book',`<section class="panel">${this.top('The Dino Book',Object.keys(p.met).length+' of '+SPECIES.length+' discoveries. Meet them to reveal their story.')}<div class="book-grid">${SPECIES.map(s=>{const known=!!p.met[s.id];return `<article class="dino-card ${known?'':'unknown'}"><div class="dino-picture" data-species="${known?s.id:''}">${known?'':'?'}</div><div><p class="eyebrow">${known?s.kind==='plant'?'ALWAYS EDIBLE':s.spiky?'ARMOURED · NEVER FOOD':'SIZE '+(s.tier!+1)+' / 7':'NOT MET YET'}</p><h2>${known?s.name:'A new discovery awaits'}</h2><p>${known?s.fact:'Take another hunt. There’s a whole valley to meet.'}</p></div></article>`}).join('')}</div>${this.nav()}${this.footer()}</section>`);for(const element of this.ui.querySelectorAll<HTMLElement>('[data-species]')){const id=element.dataset.species;if(!id)continue;const texture=this.game.textures.get('animal-'+id),frame=texture.get('0'),source=texture.getSourceImage() as HTMLCanvasElement;const canvas=document.createElement('canvas');canvas.width=160;canvas.height=160;const ctx=canvas.getContext('2d')!;ctx.drawImage(source,frame.cutX,frame.cutY,frame.cutWidth,frame.cutHeight,0,0,160,160);element.append(canvas)}}
 private leaderboard(){const rows=this.store.profiles.map(p=>({p,progress:this.store.progress(p.id)})).sort((a,b)=>b.progress.feastBest-a.progress.feastBest||totalStars(b.progress)-totalStars(a.progress));this.shell('leaderboard',`<section class="panel">${this.top('The family feast','A little friendly competition. Stars come from care, never speed.')}<div class="leaderboard">${rows.map(({p,progress},i)=>`<article class="leader-row ${p.id===this.profile?.id?'me':''}"><span class="rank">${i+1}</span><span class="avatar">${p.avatar}</span><div><h2>${esc(p.name)}</h2><p>${totalStars(progress)} stars · ${Object.keys(progress.met).length} discoveries</p></div><strong>${progress.feastBest.toLocaleString()}<small>FEAST BEST</small></strong></article>`).join('')||'<p>No hatchlings yet. Your adventure could be the first.</p>'}</div>${this.nav()}${this.footer()}</section>`)}
 private modal(content:string){document.querySelector('.modal-backdrop')?.remove();const div=document.createElement('div');div.className='modal-backdrop';div.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="Tiny Rex">${content}</section>`;this.ui.append(div);const focus=div.querySelector<HTMLElement>('input,button');focus?.focus();div.addEventListener('keydown',e=>{if(e.key==='Escape'){if(this.screen==='playing')this.action('resume');else this.action('close')}if(e.key==='Tab'){const nodes=[...div.querySelectorAll<HTMLElement>('input,select,button')];if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus()}}})}
 private help(){this.modal(`<p class="eyebrow">THE ONE QUESTION</p><h2>Is it smaller than you?</h2><div class="help-rules"><p>🟡 <b>Smaller:</b> dinner. Fill your belly and grow.</p><p>🟢 <b>Same size:</b> safe. Bump noses and carry on.</p><p>🔴 <b>Bigger:</b> run! A red ring warns you up close.</p><p>🛡 <b>Spiky:</b> never food, at any size.</p></div><p>Tap a spot or drag to move. Arrow keys or WASD work too. Escape pauses. Stars depend on hearts, not speed.</p><p>Install on iPad: Safari → Share → Add to Home Screen. Once loaded, hunts work offline. Family saves sync when connected.</p>${this.install?this.button('Install Tiny Rex','install',undefined,'primary'):''}${this.button(this.reducedMotion?'Decorative motion off':'Decorative motion on','motion',undefined,'quiet')}${this.button('Got it','close',undefined,'primary')}`)}
 private action(action:string,value?:string){
  const play=()=>this.game.scene.getScene('Play') as PlayScene;
  switch(action){case 'splash':this.splash();break;case 'profiles':this.profiles();break;case 'map':this.map();break;case 'select':this.select(value!);break;case 'new':this.newProfile();break;case 'brief':this.brief(Number(value));break;case 'start':this.start(value==='feast'?null:Number(value));break;case 'feast':this.start(null);break;case 'pause':play().requestPause();break;case 'resume':document.querySelector('.modal-backdrop')?.remove();play().resumeRun();break;case 'restart':this.start(play().sim.level?.idx??null);break;case 'quit':{const res=play().sim.end(false,'quit');if(res&&this.profile)this.store.record(this.profile.id,res);this.map();break}case 'close':document.querySelector('.modal-backdrop')?.remove();break;case 'book':this.book();break;case 'leaderboard':this.leaderboard();break;case 'help':this.help();break;case 'sound':this.audio.enabled=!this.audio.enabled;this.store.write('settings',{...this.store.settings,sound:this.audio.enabled});for(const el of this.ui.querySelectorAll('[data-action="sound"]'))el.textContent=this.audio.enabled?'♪ Sound on':'♪ Sound off';break;case 'motion':this.store.write('settings',{...this.store.settings,motion:!this.reducedMotion});this.game.registry.set('reducedMotion',this.reducedMotion);document.body.classList.toggle('reduced-motion',this.reducedMotion);this.help();break;case 'install':void this.install?.prompt();break;}
 }
}
